print("Welcome to the biography genorator!")
print("Please put all your answers in''")
print("Execpt for numbers")
name = input("What's your name? ")
print("Hi " + str(name) + ". Nice to meet you!")
age = input("How old are you? Remember to not put quotes. ")
print("So you are " + str(age) + " years old!")
fav_hobbie = input("What's your favortie hobbie? ")
print(str(fav_hobbie) + " is a really cool hobbie!")
fav_sport = input("What's your favorite sport? ")
print("Thats awesome " + str(name) + "!")
print("Your biography is almost ready!")
print("Please wait 10 seconds")
import time
time.sleep(5)
print("5 more seconds")
import time
time.sleep(5)
print(str(name) + " is really cool.")
print(str(name) + " is " + str(age) + " years old! ")
print(str(name) + "'s favorite hobbie is " + str(fav_hobbie) + ". ")
print(str(name) + "'s favorite sport is: " + str(fav_sport) + "!")
print(str(name) + " is really cool!")